/*********************************************************************
 * @file co_msg_id.h
 * @brief 
 * @version 1.0
 * @date Thu 06 Nov 2014 04:15:32 PM CST
 * @author XIHAO
 *
 * @note 
 */

#ifndef __CO_MSG_ID_H__
#define __CO_MSG_ID_H__

#ifdef __cplusplus
extern "C"
{
#endif

/*********************************************************************
 * INCLUDES
 */


/*********************************************************************
 * MACROS
 */

// OGF
#define OGF_LC                            0x0400 //(0x01 << 10) LINK CONTROL COMMANDS
#define OGF_HC                            0x0C00 //(0x03 << 10) CONTROLLER & BASEBAND COMMANDS
#define OGF_HI                            0x1000 //(0x04 << 10) INFORMATIONAL PARAMETERS
#define OGF_HS                            0x1400 //(0x05 << 10) STATUS PARAMETERS
#define OGF_LE                            0x2000 //(0x08 << 10) LE CONTROLLER COMMANDS
#define OGF_VS                            0xFC00 //(0x3F << 10) VENDOR-SPECIFIC

#define MSG_TYPE_HCI_COMMAND              1
#define MSG_TYPE_HCI_ACL                  2
#define MSG_TYPE_HCI_EVENT                4
#define MSG_TYPE_RAW_HCI                  5
#define MSG_TYPE_RAW_BB                   6
#define MSG_TYPE_BB_ADV_CHN               7
#define MSG_TYPE_BB_CTRL                  8
#define MSG_TYPE_BB_DATA                  9
#define MSG_TYPE_VENDOR_COMMAND           10
#define MSG_TYPE_VENDOR_EVENT             11

#define MSG_SUB_TYPE_HCI_EVENT_COMMON     0
#define MSG_SUB_TYPE_HCI_EVENT_COMPLETE   1
#define MSG_SUB_TYPE_HCI_EVENT_STATUS     2
#define MSG_SUB_TYPE_HCI_EVENT_META_LE    3

#define VENDOR_SG_HCI                     0
#define VENDOR_SG_L2CAP                   1
#define VENDOR_SG_ATT                     2
#define VENDOR_SG_GATT                    3
#define VENDOR_SG_GAP                     4
#define VENDOR_SG_UTIL                    5
#define VENDOR_SG_RESERVED                6
#define VENDOR_SG_PROFILE                 7

//
// MSG ID struct (32bit):
//
//    TYPE  SUB-TYPE     CODE
// |-------|-------|--------------|
// 31      23      15             0
//
#define BUILD_SYS_CMD_MSG_ID(code)        ((code) | (MSG_TYPE_HCI_COMMAND    << 24) | (0 << 16))
#define BUILD_SYS_EVT_COM_MSG_ID(code)    ((code) | (MSG_TYPE_HCI_EVENT      << 24) | (MSG_SUB_TYPE_HCI_EVENT_COMMON   << 16))
#define BUILD_SYS_EVT_CMP_MSG_ID(code)    ((code) | (MSG_TYPE_HCI_EVENT      << 24) | (MSG_SUB_TYPE_HCI_EVENT_COMPLETE << 16))
#define BUILD_SYS_EVT_STT_MSG_ID(code)    ((code) | (MSG_TYPE_HCI_EVENT      << 24) | (MSG_SUB_TYPE_HCI_EVENT_STATUS   << 16))
#define BUILD_SYS_EVT_META_MSG_ID(code)   ((code) | (MSG_TYPE_HCI_EVENT      << 24) | (MSG_SUB_TYPE_HCI_EVENT_META_LE  << 16))
#define BUILD_SYS_DAT_MSG_ID(code)        ((code) | (MSG_TYPE_HCI_ACL        << 24) | (0 << 16))
#define BUILD_SYS_RAW_HCI_MSG_ID(code)    ((code) | (MSG_TYPE_RAW_HCI        << 24) | (0 << 16))
#define BUILD_SYS_RAW_BB_MSG_ID(code)     ((code) | (MSG_TYPE_RAW_BB         << 24) | (0 << 16))
#define BUILD_SYS_BB_ADV_CHN_MSG_ID(code) ((code) | (MSG_TYPE_BB_ADV_CHN     << 24) | (0 << 16))
#define BUILD_SYS_BB_CTRL_MSG_ID(code)    ((code) | (MSG_TYPE_BB_CTRL        << 24) | (0 << 16))
#define BUILD_SYS_BB_DATA_MSG_ID(code)    ((code) | (MSG_TYPE_BB_DATA        << 24) | (0 << 16))
#define BUILD_VENDOR_CMD_MSG_ID(code)     ((code) | (MSG_TYPE_VENDOR_COMMAND << 24) | (0 << 16))
#define BUILD_VENDOR_EVT_MSG_ID(code)     ((code) | (MSG_TYPE_VENDOR_EVENT   << 24) | (0 << 16))

#define BUILD_USR_MSG_ID(code)            ((code) | (0xFFFF<<16))

#define MSGID2CODE(msg_id)                (((msg_id)>>0 ) & 0xFFFF)
#define MSGID2TYPE(msg_id)                (((msg_id)>>24) & 0xFF)
#define MSGID2SUBTYPE(msg_id)             (((msg_id)>>16) & 0xFF)
#define MSGID2OCF(msg_id)                 ((msg_id) & 0x03FF)
#define MSGID2OGF(msg_id)                 ((msg_id) & 0xFC00)
#define CODE2OCF(code)                    ((code) & 0x03FF)
#define CODE2OGF(code)                    ((code) & 0xFC00)
#define VENDOR_CODE2SG(code)              (((code)>>7)&0x0007)
#define VENDOR_CODE2OCF(code)             (((code)>>0)&0x007F)

#define VENDOR_CMD_CODE(csg, cmd)         ((cmd) + ((csg)<<7) + OGF_VS)
#define VENDOR_EVT_CODE(esg, evt)         ((evt) + ((esg)<<7) + (1<<10))

#define IS_CMP_EVT_MSG(msg_id)            ((MSGID2TYPE(msg_id) == MSG_TYPE_HCI_EVENT) && (MSGID2SUBTYPE(msg_id) == MSG_SUB_TYPE_HCI_EVENT_COMPLETE))
#define IS_STT_EVT_MSG(msg_id)            ((MSGID2TYPE(msg_id) == MSG_TYPE_HCI_EVENT) && (MSGID2SUBTYPE(msg_id) == MSG_SUB_TYPE_HCI_EVENT_STATUS))
#define IS_META_EVT_MSG(msg_id)           ((MSGID2TYPE(msg_id) == MSG_TYPE_HCI_EVENT) && (MSGID2SUBTYPE(msg_id) == MSG_SUB_TYPE_HCI_EVENT_META_LE))

#define MSGID_CMD2CMP(cmd_msg_id)         BUILD_SYS_EVT_CMP_MSG_ID(MSGID2CODE(cmd_msg_id))
#define MSGID_CMD2STT(cmd_msg_id)         BUILD_SYS_EVT_STT_MSG_ID(MSGID2CODE(cmd_msg_id))

/*********************************************************************
 * TYPEDEFS
 */

typedef enum
{
    /*****************************
     * HCI Commnad - opcodes
     ******************************/
    MSG_CMD_NOP                                     = BUILD_SYS_CMD_MSG_ID(0x0000),
    MSG_CMD_DISCONNECT                              = BUILD_SYS_CMD_MSG_ID(0x0006 + OGF_LC),
    MSG_CMD_READ_REMOTE_VER_INFO                    = BUILD_SYS_CMD_MSG_ID(0x001D + OGF_LC),
    MSG_CMD_SET_EVENT_MASK                          = BUILD_SYS_CMD_MSG_ID(0x0001 + OGF_HC),
    MSG_CMD_SET_EVENT_MASK_PAGE2                    = BUILD_SYS_CMD_MSG_ID(0x0063 + OGF_HC),
    MSG_CMD_RESET                                   = BUILD_SYS_CMD_MSG_ID(0x0003 + OGF_HC),
    MSG_CMD_READ_TRANSMIT_POWER_LEVEL               = BUILD_SYS_CMD_MSG_ID(0x002D + OGF_HC),
    MSG_CMD_SET_CONTROLLER_TO_HOST_FLOW_CONTROL     = BUILD_SYS_CMD_MSG_ID(0x0031 + OGF_HC),
    MSG_CMD_HOST_BUFFER_SIZE                        = BUILD_SYS_CMD_MSG_ID(0x0033 + OGF_HC),
    MSG_CMD_HOST_NUMBER_OF_COMPLETED_PACKETS        = BUILD_SYS_CMD_MSG_ID(0x0035 + OGF_HC),
    MSG_CMD_READ_LE_HOST_SUPPORT                    = BUILD_SYS_CMD_MSG_ID(0X006C + OGF_HC),
    MSG_CMD_READ_AUTH_PAYLOAD_TIMEOUT               = BUILD_SYS_CMD_MSG_ID(0X007B + OGF_HC),
    MSG_CMD_WRITE_AUTH_PAYLOAD_TIMEOUT              = BUILD_SYS_CMD_MSG_ID(0X007C + OGF_HC),
    MSG_CMD_READ_LOCAL_VER_INFO                     = BUILD_SYS_CMD_MSG_ID(0x0001 + OGF_HI),
    MSG_CMD_READ_LOCAL_SUPP_COMMANDS                = BUILD_SYS_CMD_MSG_ID(0x0002 + OGF_HI),
    MSG_CMD_READ_LOCAL_FEATURES                     = BUILD_SYS_CMD_MSG_ID(0x0003 + OGF_HI),
    MSG_CMD_READ_BUFFER_SIZE                        = BUILD_SYS_CMD_MSG_ID(0x0005 + OGF_HI),
    MSG_CMD_READ_BD_ADDR                            = BUILD_SYS_CMD_MSG_ID(0x0009 + OGF_HI),
    MSG_CMD_READ_RSSI                               = BUILD_SYS_CMD_MSG_ID(0x0005 + OGF_HS),
    MSG_CMD_LE_SET_EVENT_MASK                       = BUILD_SYS_CMD_MSG_ID(0x0001 + OGF_LE),
    MSG_CMD_LE_READ_BUFFER_SIZE                     = BUILD_SYS_CMD_MSG_ID(0x0002 + OGF_LE),
    MSG_CMD_LE_READ_LOCAL_SUPP_FEATURES             = BUILD_SYS_CMD_MSG_ID(0x0003 + OGF_LE),
    MSG_CMD_LE_SET_RANDOM_ADDRESS                   = BUILD_SYS_CMD_MSG_ID(0x0005 + OGF_LE),
    MSG_CMD_LE_SET_ADV_PARAM                        = BUILD_SYS_CMD_MSG_ID(0x0006 + OGF_LE),
    MSG_CMD_LE_READ_ADV_CHANNEL_TX_POWER            = BUILD_SYS_CMD_MSG_ID(0x0007 + OGF_LE),
    MSG_CMD_LE_SET_ADV_DATA                         = BUILD_SYS_CMD_MSG_ID(0x0008 + OGF_LE),
    MSG_CMD_LE_SET_SCAN_RESPONSE_DATA               = BUILD_SYS_CMD_MSG_ID(0x0009 + OGF_LE),
    MSG_CMD_LE_SET_ADV_ENABLE                       = BUILD_SYS_CMD_MSG_ID(0x000A + OGF_LE),
    MSG_CMD_LE_SET_SCAN_PARAM                       = BUILD_SYS_CMD_MSG_ID(0x000B + OGF_LE),
    MSG_CMD_LE_SET_SCAN_ENABLE                      = BUILD_SYS_CMD_MSG_ID(0x000C + OGF_LE),
    MSG_CMD_LE_CREATE_CONNECTION                    = BUILD_SYS_CMD_MSG_ID(0x000D + OGF_LE),
    MSG_CMD_LE_CREATE_CONNECTION_CANCEL             = BUILD_SYS_CMD_MSG_ID(0x000E + OGF_LE),
    MSG_CMD_LE_READ_WHITE_LIST_SIZE                 = BUILD_SYS_CMD_MSG_ID(0x000F + OGF_LE),
    MSG_CMD_LE_CLEAR_WHITE_LIST                     = BUILD_SYS_CMD_MSG_ID(0x0010 + OGF_LE),
    MSG_CMD_LE_ADD_DEVICE_TO_WHITE_LIST             = BUILD_SYS_CMD_MSG_ID(0x0011 + OGF_LE),
    MSG_CMD_LE_REMOVE_DEVICE_FROM_WHITE_LIST        = BUILD_SYS_CMD_MSG_ID(0x0012 + OGF_LE),
    MSG_CMD_LE_CON_UPDATE                           = BUILD_SYS_CMD_MSG_ID(0x0013 + OGF_LE),
    MSG_CMD_LE_SET_HOST_CHANNEL_CLASS               = BUILD_SYS_CMD_MSG_ID(0x0014 + OGF_LE),
    MSG_CMD_LE_READ_CHANNEL_MAP                     = BUILD_SYS_CMD_MSG_ID(0x0015 + OGF_LE),
    MSG_CMD_LE_READ_REMOTE_USED_FEATURES            = BUILD_SYS_CMD_MSG_ID(0x0016 + OGF_LE),
    MSG_CMD_LE_ENCRYPT                              = BUILD_SYS_CMD_MSG_ID(0x0017 + OGF_LE),
    MSG_CMD_LE_RAND                                 = BUILD_SYS_CMD_MSG_ID(0x0018 + OGF_LE),
    MSG_CMD_LE_START_ENCRYPTION                     = BUILD_SYS_CMD_MSG_ID(0x0019 + OGF_LE),
    MSG_CMD_LE_LTK_REQ_REPLY                        = BUILD_SYS_CMD_MSG_ID(0x001A + OGF_LE),
    MSG_CMD_LE_LTK_REQ_NEGATIVE_REPLY               = BUILD_SYS_CMD_MSG_ID(0x001B + OGF_LE),
    MSG_CMD_LE_READ_SUPPORTED_STATES                = BUILD_SYS_CMD_MSG_ID(0x001C + OGF_LE),
    MSG_CMD_LE_RECEIVER_TEST                        = BUILD_SYS_CMD_MSG_ID(0x001D + OGF_LE),
    MSG_CMD_LE_TRANSMITTER_TEST                     = BUILD_SYS_CMD_MSG_ID(0x001E + OGF_LE),
    MSG_CMD_LE_TEST_END                             = BUILD_SYS_CMD_MSG_ID(0x001F + OGF_LE),
    MSG_CMD_LE_CON_PARAM_REQ_REPLY                  = BUILD_SYS_CMD_MSG_ID(0x0020 + OGF_LE),
    MSG_CMD_LE_CON_PARAM_REQ_NEGATIVE_REPLY         = BUILD_SYS_CMD_MSG_ID(0x0021 + OGF_LE),
    MSG_CMD_LE_SET_DATA_LEN                         = BUILD_SYS_CMD_MSG_ID(0x0022 + OGF_LE),
    MSG_CMD_LE_READ_SUGG_DEF_DATA_LEN               = BUILD_SYS_CMD_MSG_ID(0x0023 + OGF_LE),
    MSG_CMD_LE_WRITE_SUGG_DEF_DATA_LEN              = BUILD_SYS_CMD_MSG_ID(0x0024 + OGF_LE),
    MSG_CMD_LE_READ_LOCAL_P256_PUBLIC_KEY           = BUILD_SYS_CMD_MSG_ID(0x0025 + OGF_LE),
    MSG_CMD_LE_GENERATE_DHKEY                       = BUILD_SYS_CMD_MSG_ID(0x0026 + OGF_LE),
    MSG_CMD_LE_ADD_DEVICE_TO_RESOLVE_LIST           = BUILD_SYS_CMD_MSG_ID(0x0027 + OGF_LE),
    MSG_CMD_LE_REMOVE_DEVICE_FROM_RESOLVE_LIST      = BUILD_SYS_CMD_MSG_ID(0x0028 + OGF_LE),
    MSG_CMD_LE_CLEAR_RESOLVE_LIST                   = BUILD_SYS_CMD_MSG_ID(0x0029 + OGF_LE),
    MSG_CMD_LE_READ_RESOLVE_LIST_SIZE               = BUILD_SYS_CMD_MSG_ID(0x002A + OGF_LE),
    MSG_CMD_LE_READ_PEER_RESOLVE_ADDR               = BUILD_SYS_CMD_MSG_ID(0x002B + OGF_LE),
    MSG_CMD_LE_READ_LOCAL_RESOLVE_ADDR              = BUILD_SYS_CMD_MSG_ID(0x002C + OGF_LE),
    MSG_CMD_LE_SET_ADDR_RESOLVE_ENABLE              = BUILD_SYS_CMD_MSG_ID(0x002D + OGF_LE),
    MSG_CMD_LE_SET_RESOLVE_PRIVATE_ADDR_TIMEOUT     = BUILD_SYS_CMD_MSG_ID(0x002E + OGF_LE),
    MSG_CMD_LE_READ_MAX_DATA_LEN                    = BUILD_SYS_CMD_MSG_ID(0x002F + OGF_LE),
    MSG_CMD_ILLEGAL_COMMAND                         = BUILD_SYS_CMD_MSG_ID(0xFFFF),


    /*****************************
     * HCI Events - Event codes
     ******************************/

    // msg event for common event
    MSG_EVT_DISCONNECTION_COMPLETE                  = BUILD_SYS_EVT_COM_MSG_ID(0x05),
    MSG_EVT_ENCRYPTION_CHANGE                       = BUILD_SYS_EVT_COM_MSG_ID(0x08),
    MSG_EVT_READ_REMOTE_VER_INFO_COMPLETE           = BUILD_SYS_EVT_COM_MSG_ID(0x0C),
    MSG_EVT_HARDWARE_ERROR                          = BUILD_SYS_EVT_COM_MSG_ID(0x10),
    MSG_EVT_NUMBER_OF_COMPLETED_PACKETS             = BUILD_SYS_EVT_COM_MSG_ID(0x13),
    MSG_EVT_DATA_BUFFER_OVERFLOW                    = BUILD_SYS_EVT_COM_MSG_ID(0x1A),
    MSG_EVT_ENCRYPTION_KEY_REFRESH_COMPLETE         = BUILD_SYS_EVT_COM_MSG_ID(0x30),
    MSG_EVT_AUTH_PAYLOAD_TIMEOUT_EXPIRED            = BUILD_SYS_EVT_COM_MSG_ID(0x57),

    // those event is splitted to detail msg for follow
    // MSG_EVT_COMMAND_COMPLETE                    = BUILD_SYS_EVT_COM_MSG_ID(0x0E),
    // MSG_EVT_COMMAND_STATUS                      = BUILD_SYS_EVT_COM_MSG_ID(0x0F),
    // MSG_EVT_META_LE                             = BUILD_SYS_EVT_COM_MSG_ID(0x3E),

    // msg event for command complete
    MSG_EVT_CMP_NOP                                 = MSGID_CMD2CMP(MSG_CMD_NOP),
    MSG_EVT_CMP_SET_EVENT_MASK                      = MSGID_CMD2CMP(MSG_CMD_SET_EVENT_MASK),
    MSG_EVT_CMP_SET_EVENT_MASK_PAGE2                = MSGID_CMD2CMP(MSG_CMD_SET_EVENT_MASK_PAGE2),
    MSG_EVT_CMP_RESET                               = MSGID_CMD2CMP(MSG_CMD_RESET),
    MSG_EVT_CMP_READ_TRANSMIT_POWER_LEVEL           = MSGID_CMD2CMP(MSG_CMD_READ_TRANSMIT_POWER_LEVEL),
    MSG_EVT_CMP_SET_CONTROLLER_TO_HOST_FLOW_CONTROL = MSGID_CMD2CMP(MSG_CMD_SET_CONTROLLER_TO_HOST_FLOW_CONTROL),
    MSG_EVT_CMP_HOST_BUFFER_SIZE                    = MSGID_CMD2CMP(MSG_CMD_HOST_BUFFER_SIZE),
    MSG_EVT_CMP_HOST_NUMBER_OF_COMPLETED_PACKETS    = MSGID_CMD2CMP(MSG_CMD_HOST_NUMBER_OF_COMPLETED_PACKETS),
    MSG_EVT_CMP_READ_LE_HOST_SUPPORT                = MSGID_CMD2CMP(MSG_CMD_READ_LE_HOST_SUPPORT),
    MSG_EVT_CMP_READ_AUTH_PAYLOAD_TIMEOUT           = MSGID_CMD2CMP(MSG_CMD_READ_AUTH_PAYLOAD_TIMEOUT),
    MSG_EVT_CMP_WRITE_AUTH_PAYLOAD_TIMEOUT          = MSGID_CMD2CMP(MSG_CMD_WRITE_AUTH_PAYLOAD_TIMEOUT),
    MSG_EVT_CMP_READ_LOCAL_VER_INFO                 = MSGID_CMD2CMP(MSG_CMD_READ_LOCAL_VER_INFO),
    MSG_EVT_CMP_READ_LOCAL_SUPP_COMMANDS            = MSGID_CMD2CMP(MSG_CMD_READ_LOCAL_SUPP_COMMANDS),
    MSG_EVT_CMP_READ_LOCAL_FEATURES                 = MSGID_CMD2CMP(MSG_CMD_READ_LOCAL_FEATURES),
    MSG_EVT_CMP_READ_BUFFER_SIZE                    = MSGID_CMD2CMP(MSG_CMD_READ_BUFFER_SIZE),
    MSG_EVT_CMP_READ_BD_ADDR                        = MSGID_CMD2CMP(MSG_CMD_READ_BD_ADDR),
    MSG_EVT_CMP_READ_RSSI                           = MSGID_CMD2CMP(MSG_CMD_READ_RSSI),
    MSG_EVT_CMP_LE_SET_EVENT_MASK                   = MSGID_CMD2CMP(MSG_CMD_LE_SET_EVENT_MASK),
    MSG_EVT_CMP_LE_READ_BUFFER_SIZE                 = MSGID_CMD2CMP(MSG_CMD_LE_READ_BUFFER_SIZE),
    MSG_EVT_CMP_LE_READ_LOCAL_SUPP_FEATURES         = MSGID_CMD2CMP(MSG_CMD_LE_READ_LOCAL_SUPP_FEATURES),
    MSG_EVT_CMP_LE_SET_RANDOM_ADDRESS               = MSGID_CMD2CMP(MSG_CMD_LE_SET_RANDOM_ADDRESS),
    MSG_EVT_CMP_LE_SET_ADV_PARAM                    = MSGID_CMD2CMP(MSG_CMD_LE_SET_ADV_PARAM),
    MSG_EVT_CMP_LE_READ_ADV_CHANNEL_TX_POWER        = MSGID_CMD2CMP(MSG_CMD_LE_READ_ADV_CHANNEL_TX_POWER),
    MSG_EVT_CMP_LE_SET_ADV_DATA                     = MSGID_CMD2CMP(MSG_CMD_LE_SET_ADV_DATA),
    MSG_EVT_CMP_LE_SET_SCAN_RESPONSE_DATA           = MSGID_CMD2CMP(MSG_CMD_LE_SET_SCAN_RESPONSE_DATA),
    MSG_EVT_CMP_LE_SET_ADV_ENABLE                   = MSGID_CMD2CMP(MSG_CMD_LE_SET_ADV_ENABLE),
    MSG_EVT_CMP_LE_SET_SCAN_PARAM                   = MSGID_CMD2CMP(MSG_CMD_LE_SET_SCAN_PARAM),
    MSG_EVT_CMP_LE_SET_SCAN_ENABLE                  = MSGID_CMD2CMP(MSG_CMD_LE_SET_SCAN_ENABLE),
    MSG_EVT_CMP_LE_CREATE_CONNECTION_CANCEL         = MSGID_CMD2CMP(MSG_CMD_LE_CREATE_CONNECTION_CANCEL),
    MSG_EVT_CMP_LE_READ_WHITE_LIST_SIZE             = MSGID_CMD2CMP(MSG_CMD_LE_READ_WHITE_LIST_SIZE),
    MSG_EVT_CMP_LE_CLEAR_WHITE_LIST                 = MSGID_CMD2CMP(MSG_CMD_LE_CLEAR_WHITE_LIST),
    MSG_EVT_CMP_LE_ADD_DEVICE_TO_WHITE_LIST         = MSGID_CMD2CMP(MSG_CMD_LE_ADD_DEVICE_TO_WHITE_LIST),
    MSG_EVT_CMP_LE_REMOVE_DEVICE_FROM_WHITE_LIST    = MSGID_CMD2CMP(MSG_CMD_LE_REMOVE_DEVICE_FROM_WHITE_LIST),
    MSG_EVT_CMP_LE_SET_HOST_CHANNEL_CLASS           = MSGID_CMD2CMP(MSG_CMD_LE_SET_HOST_CHANNEL_CLASS),
    MSG_EVT_CMP_LE_READ_CHANNEL_MAP                 = MSGID_CMD2CMP(MSG_CMD_LE_READ_CHANNEL_MAP),
    MSG_EVT_CMP_LE_ENCRYPT                          = MSGID_CMD2CMP(MSG_CMD_LE_ENCRYPT),
    MSG_EVT_CMP_LE_RAND                             = MSGID_CMD2CMP(MSG_CMD_LE_RAND),
    MSG_EVT_CMP_LE_LTK_REQ_REPLY                    = MSGID_CMD2CMP(MSG_CMD_LE_LTK_REQ_REPLY),
    MSG_EVT_CMP_LE_LTK_REQ_NEGATIVE_REPLY           = MSGID_CMD2CMP(MSG_CMD_LE_LTK_REQ_NEGATIVE_REPLY),
    MSG_EVT_CMP_LE_READ_SUPPORTED_STATES            = MSGID_CMD2CMP(MSG_CMD_LE_READ_SUPPORTED_STATES),
    MSG_EVT_CMP_LE_RECEIVER_TEST                    = MSGID_CMD2CMP(MSG_CMD_LE_RECEIVER_TEST),
    MSG_EVT_CMP_LE_TRANSMITTER_TEST                 = MSGID_CMD2CMP(MSG_CMD_LE_TRANSMITTER_TEST),
    MSG_EVT_CMP_LE_TEST_END                         = MSGID_CMD2CMP(MSG_CMD_LE_TEST_END),
    MSG_EVT_CMP_LE_CON_PARAM_REQ_REPLY              = MSGID_CMD2CMP(MSG_CMD_LE_CON_PARAM_REQ_REPLY),
    MSG_EVT_CMP_LE_CON_PARAM_REQ_NEGATIVE_REPLY     = MSGID_CMD2CMP(MSG_CMD_LE_CON_PARAM_REQ_NEGATIVE_REPLY),
    MSG_EVT_CMP_LE_SET_DATA_LEN                     = MSGID_CMD2CMP(MSG_CMD_LE_SET_DATA_LEN),
    MSG_EVT_CMP_LE_READ_SUGG_DEF_DATA_LEN           = MSGID_CMD2CMP(MSG_CMD_LE_READ_SUGG_DEF_DATA_LEN),
    MSG_EVT_CMP_LE_WRITE_SUGG_DEF_DATA_LEN          = MSGID_CMD2CMP(MSG_CMD_LE_WRITE_SUGG_DEF_DATA_LEN),
    MSG_EVT_CMP_LE_ADD_DEVICE_TO_RESOLVE_LIST       = MSGID_CMD2CMP(MSG_CMD_LE_ADD_DEVICE_TO_RESOLVE_LIST),
    MSG_EVT_CMP_LE_REMOVE_DEVICE_FROM_RESOLVE_LIST  = MSGID_CMD2CMP(MSG_CMD_LE_REMOVE_DEVICE_FROM_RESOLVE_LIST),
    MSG_EVT_CMP_LE_CLEAR_RESOLVE_LIST               = MSGID_CMD2CMP(MSG_CMD_LE_CLEAR_RESOLVE_LIST),
    MSG_EVT_CMP_LE_READ_RESOLVE_LIST_SIZE           = MSGID_CMD2CMP(MSG_CMD_LE_READ_RESOLVE_LIST_SIZE),
    MSG_EVT_CMP_LE_READ_PEER_RESOLVE_ADDR           = MSGID_CMD2CMP(MSG_CMD_LE_READ_PEER_RESOLVE_ADDR),
    MSG_EVT_CMP_LE_READ_LOCAL_RESOLVE_ADDR          = MSGID_CMD2CMP(MSG_CMD_LE_READ_LOCAL_RESOLVE_ADDR),
    MSG_EVT_CMP_LE_SET_ADDR_RESOLVE_ENABLE          = MSGID_CMD2CMP(MSG_CMD_LE_SET_ADDR_RESOLVE_ENABLE),
    MSG_EVT_CMP_LE_SET_RESOLVE_PRIVATE_ADDR_TIMEOUT = MSGID_CMD2CMP(MSG_CMD_LE_SET_RESOLVE_PRIVATE_ADDR_TIMEOUT),
    MSG_EVT_CMP_LE_READ_MAX_DATA_LEN                = MSGID_CMD2CMP(MSG_CMD_LE_READ_MAX_DATA_LEN),

    // msg event for command status
    MSG_EVT_STT_DISCONNECT                          = MSGID_CMD2STT(MSG_CMD_DISCONNECT),
    MSG_EVT_STT_READ_REMOTE_VER_INFO                = MSGID_CMD2STT(MSG_CMD_READ_REMOTE_VER_INFO),
    MSG_EVT_STT_LE_CREATE_CONNECTION                = MSGID_CMD2STT(MSG_CMD_LE_CREATE_CONNECTION),
    MSG_EVT_STT_LE_READ_REMOTE_USED_FEATURES        = MSGID_CMD2STT(MSG_CMD_LE_READ_REMOTE_USED_FEATURES),
    MSG_EVT_STT_LE_CON_UPDATE                       = MSGID_CMD2STT(MSG_CMD_LE_CON_UPDATE),
    MSG_EVT_STT_LE_START_ENCRYPTION                 = MSGID_CMD2STT(MSG_CMD_LE_START_ENCRYPTION),
    MSG_EVT_STT_LE_READ_LOCAL_P256_PUBLIC_KEY       = MSGID_CMD2STT(MSG_CMD_LE_READ_LOCAL_P256_PUBLIC_KEY),
    MSG_EVT_STT_LE_GENERATE_DHKEY                   = MSGID_CMD2STT(MSG_CMD_LE_GENERATE_DHKEY),

    // msg event for le meta
    MSG_EVT_META_LE_CONNECTION_COMPLETE             = BUILD_SYS_EVT_META_MSG_ID(0x01),
    MSG_EVT_META_LE_ADV_REPORT                      = BUILD_SYS_EVT_META_MSG_ID(0x02),
    MSG_EVT_META_LE_CON_UPDATE_COMPLETE             = BUILD_SYS_EVT_META_MSG_ID(0x03),
    MSG_EVT_META_LE_READ_REMOTE_USED_FEATURES       = BUILD_SYS_EVT_META_MSG_ID(0x04),
    MSG_EVT_META_LE_LTK_REQ                         = BUILD_SYS_EVT_META_MSG_ID(0x05),
    MSG_EVT_META_LE_REMOTE_CON_PARAM_REQ            = BUILD_SYS_EVT_META_MSG_ID(0x06),
    MSG_EVT_META_LE_DATA_LENGTH_CHANGE              = BUILD_SYS_EVT_META_MSG_ID(0x07),
    MSG_EVT_META_LE_READ_LOCAL_P256_PUBLIC_KEY      = BUILD_SYS_EVT_META_MSG_ID(0x08),
    MSG_EVT_META_LE_GENERATE_DHKEY                  = BUILD_SYS_EVT_META_MSG_ID(0x09),
    MSG_EVT_META_LE_ENHANCED_CONNECTION_COMPLETE    = BUILD_SYS_EVT_META_MSG_ID(0x0A),
    MSG_EVT_META_LE_DIRECT_ADV_REPORT               = BUILD_SYS_EVT_META_MSG_ID(0x0B),

    /*****************************
     * HCI ACL DATA
     ******************************/
    MSG_ACL_DATA                                    = BUILD_SYS_DAT_MSG_ID(0),

    /*****************************
     * HCI RAW DATA
     ******************************/
    MSG_RAW_HCI                                     = BUILD_SYS_RAW_HCI_MSG_ID(0),
    MSG_RAW_ACI                                     = MSG_RAW_HCI,

    /*****************************
     * BB ADV CHENNEL COMMAND
     ******************************/
    MSG_BB_ADV_IND                                  = BUILD_SYS_BB_ADV_CHN_MSG_ID(0x00),
    MSG_BB_ADV_DIRECT_IND                           = BUILD_SYS_BB_ADV_CHN_MSG_ID(0x01),
    MSG_BB_ADV_NONCONN_IND                          = BUILD_SYS_BB_ADV_CHN_MSG_ID(0x02),
    MSG_BB_SCAN_REQ                                 = BUILD_SYS_BB_ADV_CHN_MSG_ID(0x03),
    MSG_BB_SCAN_RSP                                 = BUILD_SYS_BB_ADV_CHN_MSG_ID(0x04),
    MSG_BB_INIT_CONNECT_REQ                         = BUILD_SYS_BB_ADV_CHN_MSG_ID(0x05),
    MSG_BB_ADV_SCAN_IND                             = BUILD_SYS_BB_ADV_CHN_MSG_ID(0x06),

    /*****************************
     * BB DATA CHENNEL CONTROL COMMAND
     ******************************/
    MSG_BB_CTRL_LL_CON_UPDATE_REQ                   = BUILD_SYS_BB_CTRL_MSG_ID(0x00),
    MSG_BB_CTRL_LL_CHANNEL_MAP_REQ                  = BUILD_SYS_BB_CTRL_MSG_ID(0x01),
    MSG_BB_CTRL_LL_TERMINATE_IND                    = BUILD_SYS_BB_CTRL_MSG_ID(0x02),
    MSG_BB_CTRL_LL_ENC_REQ                          = BUILD_SYS_BB_CTRL_MSG_ID(0x03),
    MSG_BB_CTRL_LL_ENC_RSP                          = BUILD_SYS_BB_CTRL_MSG_ID(0x04),
    MSG_BB_CTRL_LL_START_ENC_REQ                    = BUILD_SYS_BB_CTRL_MSG_ID(0x05),
    MSG_BB_CTRL_LL_START_ENC_RSP                    = BUILD_SYS_BB_CTRL_MSG_ID(0x06),
    MSG_BB_CTRL_LL_UNKNOWN_RSP                      = BUILD_SYS_BB_CTRL_MSG_ID(0x07),
    MSG_BB_CTRL_LL_FEATURE_REQ                      = BUILD_SYS_BB_CTRL_MSG_ID(0x08),
    MSG_BB_CTRL_LL_FEATURE_RSP                      = BUILD_SYS_BB_CTRL_MSG_ID(0x09),
    MSG_BB_CTRL_LL_PAUSE_ENC_REQ                    = BUILD_SYS_BB_CTRL_MSG_ID(0x0A),
    MSG_BB_CTRL_LL_PAUSE_ENC_RSP                    = BUILD_SYS_BB_CTRL_MSG_ID(0x0B),
    MSG_BB_CTRL_LL_VERSION_IND                      = BUILD_SYS_BB_CTRL_MSG_ID(0x0C),
    MSG_BB_CTRL_LL_REJECT_IND                       = BUILD_SYS_BB_CTRL_MSG_ID(0x0D),
    MSG_BB_CTRL_LL_SLAVE_FEATURE_REQ                = BUILD_SYS_BB_CTRL_MSG_ID(0x0E),
    MSG_BB_CTRL_LL_CON_PARAM_REQ                    = BUILD_SYS_BB_CTRL_MSG_ID(0x0F),
    MSG_BB_CTRL_LL_CON_PARAM_RSP                    = BUILD_SYS_BB_CTRL_MSG_ID(0x10),
    MSG_BB_CTRL_LL_REJECT_IND_EXT                   = BUILD_SYS_BB_CTRL_MSG_ID(0x11),
    MSG_BB_CTRL_LL_PING_REQ                         = BUILD_SYS_BB_CTRL_MSG_ID(0x12),
    MSG_BB_CTRL_LL_PING_RSP                         = BUILD_SYS_BB_CTRL_MSG_ID(0x13),
    MSG_BB_CTRL_LL_LENGTH_REQ                       = BUILD_SYS_BB_CTRL_MSG_ID(0x14),
    MSG_BB_CTRL_LL_LENGTH_RSP                       = BUILD_SYS_BB_CTRL_MSG_ID(0x15),
    MSG_BB_CTRL_LL_ILLEGAL_CMD                      = BUILD_SYS_BB_CTRL_MSG_ID(0xFF),

    /*****************************
     * BB DATA CHENNEL DATA
     ******************************/
    MSG_BB_DATA                                     = BUILD_SYS_BB_DATA_MSG_ID(0),

    /*****************************
     * BB RAW DATA
     ******************************/
    MSG_RAW_BB_ADV_CHN                              = BUILD_SYS_RAW_BB_MSG_ID(0),
    MSG_RAW_BB_DAT_CHN                              = BUILD_SYS_RAW_BB_MSG_ID(1),


    /*****************************
     * VENDOR-SPECIFIC Commands
     ******************************/
    // 15              10 9        7 6                       0
    // +-----------------+----------+------------------------+
    // |     111111b     |    CSG   |          CMD           |
    // +-----------------+----------+------------------------+
    //                     Opcode
    MSG_CMD_SET_RX_GAIN                               = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 0 )), //0xFC00
    MSG_CMD_SET_TX_POWER                              = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 1 )), //0xFC01
    MSG_CMD_ONE_PACKET_PER_EVENT                      = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 2 )), //0xFC02
    MSG_CMD_CLOCK_DIVIDE_ON_HALT                      = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 3 )), //0xFC03
    MSG_CMD_DECLARE_NV_USAGE                          = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 4 )), //0xFC04
    MSG_CMD_DECRYPT                                   = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 5 )), //0xFC05
    MSG_CMD_SET_LOCAL_SUPPORTED_FEATURES              = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 6 )), //0xFC06
    MSG_CMD_SET_FAST_TX_RESPONSE_TIME                 = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 7 )), //0xFC07
    MSG_CMD_MODEM_TEST_TX                             = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 8 )), //0xFC08
    MSG_CMD_MODEM_HOP_TEST_TX                         = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 9 )), //0xFC09
    MSG_CMD_MODEM_TEST_RX                             = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 10)), //0xFC0A
    MSG_CMD_END_MODEM_TEST                            = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 11)), //0xFC0B
    MSG_CMD_SET_BDADDR                                = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 12)), //0xFC0C
    MSG_CMD_SET_SCA                                   = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 13)), //0xFC0D
    MSG_CMD_ENABLE_PTM1                               = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 14)), //0xFC0E
    MSG_CMD_SET_FREQUENCY_TUNING                      = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 15)), //0xFC0F
    MSG_CMD_SAVE_FREQUENCY_TUNING                     = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 16)), //0xFC10
    MSG_CMD_SET_MAX_DTM_TX_POWER                      = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 17)), //0xFC11
    MSG_CMD_MAP_PM_IO_PORT                            = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 18)), //0xFC12
    MSG_CMD_DISCONNECT_IMMEDIATE                      = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 19)), //0xFC13
    MSG_CMD_PACKET_ERROR_RATE                         = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 20)), //0xFC14
    MSG_CMD_PACKET_ERROR_RATE_BY_CHANNEL2             = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 21)), //0xFC15
    MSG_CMD_EXTEND_RF_RANGE                           = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 22)), //0xFC16
    MSG_CMD_ADVERTISER_EVENT_NOTICE2                  = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 23)), //0xFC17
    MSG_CMD_CONNECTION_EVENT_NOTICE2                  = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 24)), //0xFC18
    MSG_CMD_HALT_DURING_RF                            = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 25)), //0xFC19
    MSG_CMD_SET_SLAVE_LATENCY_OVERRIDE                = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 26)), //0xFC1A
    MSG_CMD_BUILD_REVISION                            = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 27)), //0xFC1B
    MSG_CMD_DELAY_SLEEP                               = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 28)), //0xFC1C
    MSG_CMD_RESET_SYSTEM                              = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 29)), //0xFC1D
    MSG_CMD_OVERLAPPED_PROCESSING                     = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 30)), //0xFC1E
    MSG_CMD_NUMBER_COMPLETED_PACKETS_LIMIT            = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(0, 31)), //0xFC1F

    MSG_CMD_L2CAP_CONNECTION_PARAMETER_UPDATE_REQUEST = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(1, 18)), //0xFC92
    MSG_CMD_L2CAP_INI_CREDIT_BASED_CONNECT_REQUEST    = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(1, 19)), //0xFC93
    MSG_CMD_L2CAP_LE_CREDIT_BASED_CONNECT_RSP         = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(1, 20)), //0XFC94
    MSG_CMD_L2CAP_CONN_PARA_UPDATE_RSP                = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(1, 21)), //0XFC95
    MSG_CMD_L2CAP_LE_FLOW_CTRL_CREDIT                 = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(1, 22)), //0XFC96
    MSG_CMD_L2CAP_DATA_REQ                            = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(1, 23)), //0XFC97
    MSG_CMD_L2CAP_PROCESS_SEND_DATA                   = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(1, 24)), //0XFC98



    MSG_CMD_ATT_ERROR_RESPONSE                        = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(2, 1 )), //0xFD01
    MSG_CMD_ATT_EXCHANGE_MTU_REQUEST                  = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(2, 2 )), //0xFD02
    MSG_CMD_ATT_EXCHANGE_MTU_RESPONSE                 = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(2, 3 )), //0xFD03
    MSG_CMD_ATT_FIND_INFORMATION_REQUEST              = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(2, 4 )), //0xFD04
    MSG_CMD_ATT_FIND_INFORMATION_RESPONSE             = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(2, 5 )), //0xFD05
    MSG_CMD_ATT_FIND_BY_TYPE_VALUE_REQUEST            = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(2, 6 )), //0xFD06
    MSG_CMD_ATT_FIND_BY_TYPE_VALUE_RESPONSE           = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(2, 7 )), //0xFD07
    MSG_CMD_ATT_READ_BY_TYPE_REQUEST                  = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(2, 8 )), //0xFD08
    MSG_CMD_ATT_READ_BY_TYPE_RESPONSE                 = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(2, 9 )), //0xFD09
    MSG_CMD_ATT_READ_REQUEST                          = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(2, 10)), //0xFD0A
    MSG_CMD_ATT_READ_RESPONSE                         = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(2, 11)), //0xFD0B
    MSG_CMD_ATT_READ_BLOB_REQUEST                     = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(2, 12)), //0xFD0C
    MSG_CMD_ATT_READ_BLOB_RESPONSE                    = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(2, 13)), //0xFD0D
    MSG_CMD_ATT_READ_MULTIPLE_REQUEST                 = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(2, 14)), //0xFD0E
    MSG_CMD_ATT_READ_MULTIPLE_RESPONSE                = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(2, 15)), //0xFD0F
    MSG_CMD_ATT_READ_BY_GROUP_TYPE_REQUEST            = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(2, 16)), //0xFD10
    MSG_CMD_ATT_READ_BY_GROUP_TYPE_RESPONSE           = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(2, 17)), //0xFD11
    MSG_CMD_ATT_WRITE_REQUEST                         = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(2, 18)), //0xFD12
    MSG_CMD_ATT_WRITE_RESPONSE                        = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(2, 19)), //0xFD13
    MSG_CMD_ATT_PREPARE_WRITE_REQUEST                 = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(2, 22)), //0xFD16
    MSG_CMD_ATT_PREPARE_WRITE_RESPONSE                = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(2, 23)), //0xFD17
    MSG_CMD_ATT_EXECUTE_WRITE_REQUEST                 = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(2, 24)), //0xFD18
    MSG_CMD_ATT_EXECUTE_WRITE_RESPONSE                = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(2, 25)), //0xFD19
    MSG_CMD_ATT_HANDLE_VALUE_NOTIFICATION             = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(2, 27)), //0xFD1B
    MSG_CMD_ATT_HANDLE_VALUE_INDICATION               = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(2, 29)), //0xFD1D
    MSG_CMD_ATT_HANDLE_VALUE_CONFIRMATION             = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(2, 30)), //0xFD1E

    MSG_CMD_GATT_PTS_DATA_BASE_INI                    = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 1 )), //0xFD81
    MSG_CMD_GATT_EXCHANGE_MTU                         = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 2 )), //0xFD82
    MSG_CMD_GATT_DISC_ALL_PRIMARY_SERVICES            = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 16)), //0xFD90
    MSG_CMD_GATT_DISC_PRIMARY_SERVICE_BY_UUID         = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 6 )), //0xFD86
    MSG_CMD_GATT_FIND_INCLUDED_SERVICES               = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 48)), //0xFDB0
    MSG_CMD_GATT_DISC_ALL_CHARS                       = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 50)), //0xFDB2
    MSG_CMD_GATT_DISC_ALL_CHAR_DESCS                  = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 4 )), //0xFD84
    MSG_CMD_GATT_READ_CHAR_VALUE                      = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 10)), //0xFD8A
    MSG_CMD_GATT_READ_USING_CHAR_UUID                 = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 52)), //0xFDB4
    MSG_CMD_GATT_READ_LONG_CHAR_VALUE                 = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 12)), //0xFD8C
    MSG_CMD_GATT_READ_MULTI_CHAR_VALUES               = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 14)), //0xFD8E
    MSG_CMD_GATT_WRITE_NO_RSP                         = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 54)), //0xFDB6
    MSG_CMD_GATT_SIGNED_WRITE_NO_RSP                  = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 56)), //0xFDB8
    MSG_CMD_GATT_WRITE_CHAR_VALUE                     = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 18)), //0xFD92
    MSG_CMD_GATT_WRITE_LONG_CHAR_VALUE                = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 22)), //0xFD92
    MSG_CMD_GATT_RELIABLE_WRITES                      = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 58)), //0xFDBA
    MSG_CMD_GATT_READ_CHAR_DESC                       = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 60)), //0xFDBC
    MSG_CMD_GATT_READ_LONG_CHAR_DESC                  = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 62)), //0xFDBE
    MSG_CMD_GATT_WRITE_CHAR_DESC                      = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 64)), //0xFDC0
    MSG_CMD_GATT_WRITE_LONG_CHAR_DESC                 = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 66)), //0xFDC2
    MSG_CMD_GATT_NOTIFICATION                         = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 27)), //0xFD9B
    MSG_CMD_GATT_INDICATION                           = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 29)), //0xFD9D
    MSG_CMD_GATT_ADD_SERVICE                          = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 124)),//0XFDFC
    MSG_CMD_GATT_DEL_SERVICE                          = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 125)),//0XFDFD
    MSG_CMD_GATT_ADD_ATTRIBUTE                        = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 126)),//0XFDFE
    MSG_CMD_GATT_DISCOVER_CHARACTERISTICS_BY_UUID     = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 8 )), //0xFD88
//    MSG_CMD_GATT_WRITE_LONG                           = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(3, 22)), //0xFD96

    MSG_CMD_GAP_DEVICE_INITIALIZATION                 = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(4, 0 )), //0xFE00
    MSG_CMD_GAP_CONFIGURE_DEVICE_ADDRESS              = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(4, 3 )), //0xFE03
    MSG_CMD_GAP_DEVICE_DISCOVERY_REQUEST              = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(4, 4 )), //0xFE04
    MSG_CMD_GAP_DEVICE_DISCOVERY_CANCEL               = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(4, 5 )), //0xFE05
    MSG_CMD_GAP_MAKE_DISCOVERABLE                     = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(4, 6 )), //0xFE06
    MSG_CMD_GAP_UPDATE_ADVERTISING_DATA               = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(4, 7 )), //0xFE07
    MSG_CMD_GAP_END_DISCOVERABLE                      = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(4, 8 )), //0xFE08
    MSG_CMD_GAP_ESTABLISH_LINK_REQUEST                = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(4, 9 )), //0xFE09
    MSG_CMD_GAP_TERMINATE_LINK_REQUEST                = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(4, 10)), //0xFE0A
    MSG_CMD_GAP_AUTHENTICATE                          = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(4, 11)), //0xFE0B
    MSG_CMD_GAP_PASSKEY_UPDATE                        = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(4, 12)), //0xFE0C
    MSG_CMD_GAP_SLAVE_SECURITY_REQUEST                = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(4, 13)), //0xFE0D
    MSG_CMD_GAP_SIGNABLE                              = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(4, 14)), //0xFE0E
    MSG_CMD_GAP_BOND                                  = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(4, 15)), //0xFE0F
    MSG_CMD_GAP_TERMINATE_AUTH                        = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(4, 16)), //0xFE10
    MSG_CMD_GAP_UPDATE_LINK_PARAMETER_REQUEST         = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(4, 17)), //0xFE11
    MSG_CMD_GAP_SET_PARAMETER                         = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(4, 48)), //0xFE30
    MSG_CMD_GAP_GET_PARAMETER                         = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(4, 49)), //0xFE31
    MSG_CMD_GAP_RESOLVE_PRIVATE_ADDRESS               = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(4, 50)), //0xFE32
    MSG_CMD_GAP_SET_ADVERTISEMENT_TOKEN               = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(4, 51)), //0xFE33
    MSG_CMD_GAP_REMOVE_ADVERTISEMENT_TOKEN            = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(4, 52)), //0xFE34
    MSG_CMD_GAP_UPDATE_ADVERTISEMENT_TOKENS           = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(4, 53)), //0xFE35
    MSG_CMD_GAP_BOND_SET_PARAMETER                    = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(4, 54)), //0xFE36
    MSG_CMD_GAP_BOND_GET_PARAMETER                    = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(4, 55)), //0xFE37

    MSG_CMD_UTIL_RESERVED                             = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(5, 0 )), //0xFE80
    MSG_CMD_UTIL_NV_READ                              = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(5, 1 )), //0xFE81
    MSG_CMD_UTIL_NV_WRITE                             = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(5, 2 )), //0xFE82

    MSG_CMD_RESERVED                                  = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(6, 0 )), //0xFF00


    /*****************************
     * VENDOR-SPECIFIC Events
     ******************************/
    // 7     0 7       0    15   10 9   7 6    0
    // +------+--------+    +------+-----+-----+
    // | 0xFF | Length | -- | EOGF | ESG | EVT |
    // +------+--------+    +------+-----+-----+
    //                             Opcode
    MSG_EVT_SET_RX_GAIN                                = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 0 )), //0x0400
    MSG_EVT_SET_TX_POWER                               = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 1 )), //0x0401
    MSG_EVT_ONE_PACKET_PER_EVENT                       = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 2 )), //0x0402
    MSG_EVT_CLOCK_DIVIDE_ON_HALT                       = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 3 )), //0x0403
    MSG_EVT_DECLARE_NV_USAGE                           = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 4 )), //0x0404
    MSG_EVT_DECRYPT                                    = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 5 )), //0x0405
    MSG_EVT_SET_LOCAL_SUPPORTED_FEATURES               = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 6 )), //0x0406
    MSG_EVT_SET_FAST_TX_RESPONSE_TIME                  = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 7 )), //0x0407
    MSG_EVT_MODEM_TEST_TX                              = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 8 )), //0x0408
    MSG_EVT_MODEM_HOP_TEST_TX                          = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 9 )), //0x0409
    MSG_EVT_MODEM_TEST_RX                              = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 10)), //0x040A
    MSG_EVT_END_MODEM_TEST                             = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 11)), //0x040B
    MSG_EVT_SET_BDADDR                                 = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 12)), //0x040C
    MSG_EVT_SET_SCA                                    = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 13)), //0x040D
    MSG_EVT_ENABLE_PTM3                                = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 14)), //0x040E
    MSG_EVT_SET_FREQUENCY_TUNING                       = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 15)), //0x040F
    MSG_EVT_SAVE_FREQUENCY_TUNING                      = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 16)), //0x0410
    MSG_EVT_SET_MAX_DTM_TX_POWER                       = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 17)), //0x0411
    MSG_EVT_MAP_PM_IO_PORT                             = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 18)), //0x0412
    MSG_EVT_DISCONNECT_IMMEDIATE                       = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 19)), //0x0413
    MSG_EVT_PACKET_ERROR_RATE                          = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 20)), //0x0414
    MSG_EVT_PACKET_ERROR_RATE_BY_CHANNEL3              = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 21)), //0x0415
    MSG_EVT_EXTEND_RF_RANGE                            = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 22)), //0x0416
    MSG_EVT_ADVERTISER_EVENT_NOTICE3                   = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 23)), //0x0417
    MSG_EVT_CONNECTION_EVENT_NOTICE3                   = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 24)), //0x0418
    MSG_EVT_HALT_DURING_RF                             = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 25)), //0x0419
    MSG_EVT_SET_SLAVE_LATENCY_OVERRIDE                 = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 26)), //0x041A
    MSG_EVT_BUILD_REVISION                             = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 27)), //0x041B
    MSG_EVT_DELAY_SLEEP                                = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 28)), //0x041C
    MSG_EVT_RESET_SYSTEM                               = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 29)), //0x041D
    MSG_EVT_OVERLAPPED_PROCESSING                      = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 30)), //0x041E
    MSG_EVT_NUMBER_COMPLETED_PACKETS_LIMIT             = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(0, 31)), //0x041F

    MSG_EVT_L2CAP_COMMAND_REJECT                       = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(1, 1 )), //0x0481
    MSG_EVT_L2CAP_INFO_RSP                             = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(1, 12 )), //0x048B
    MSG_EVT_L2CAP_CONNECTION_PARAMETER_UPDATE_RESPONSE = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(1, 19)), //0x0493

    MSG_EVT_ATT_ERROR_RESPONSE                         = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(2, 1 )), //0x0501
    MSG_EVT_ATT_EXCHANGE_MTU_REQUEST                   = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(2, 2 )), //0x0502
    MSG_EVT_ATT_EXCHANGE_MTU_RESPONSE                  = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(2, 3 )), //0x0503
    MSG_EVT_ATT_FIND_INFORMATION_REQUEST               = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(2, 4 )), //0x0504
    MSG_EVT_ATT_FIND_INFORMATION_RESPONSE              = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(2, 5 )), //0x0505
    MSG_EVT_ATT_FIND_BY_TYPE_VALUE_REQUEST             = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(2, 6 )), //0x0506
    MSG_EVT_ATT_FIND_BY_TYPE_VALUE_RESPONSE            = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(2, 7 )), //0x0507
    MSG_EVT_ATT_READ_BY_TYPE_REQUEST                   = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(2, 8 )), //0x0508
    MSG_EVT_ATT_READ_BY_TYPE_RESPONSE                  = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(2, 9 )), //0x0509
    MSG_EVT_ATT_READ_REQUEST                           = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(2, 10)), //0x050A
    MSG_EVT_ATT_READ_RESPONSE                          = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(2, 11)), //0x050B
    MSG_EVT_ATT_READ_BLOB_REQUEST                      = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(2, 12)), //0x050C
    MSG_EVT_ATT_READ_BLOB_RESPONSE                     = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(2, 13)), //0x050D
    MSG_EVT_ATT_READ_MULTIPLE_REQUEST                  = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(2, 14)), //0x050E
    MSG_EVT_ATT_READ_MULTIPLE_RESPONSE                 = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(2, 15)), //0x050F
    MSG_EVT_ATT_READ_BY_GROUP_TYPE_REQUEST             = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(2, 16)), //0x0510
    MSG_EVT_ATT_READ_BY_GROUP_TYPE_RESPONSE            = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(2, 17)), //0x0511
    MSG_EVT_ATT_WRITE_REQUEST                          = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(2, 18)), //0x0512
    MSG_EVT_ATT_WRITE_RESPONSE                         = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(2, 19)), //0x0513
    MSG_EVT_ATT_PREPARE_WRITE_REQUEST                  = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(2, 22)), //0x0516
    MSG_EVT_ATT_PREPARE_WRITE_RESPONSE                 = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(2, 23)), //0x0517
    MSG_EVT_ATT_EXECUTE_WRITE_REQUEST                  = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(2, 24)), //0x0518
    MSG_EVT_ATT_EXECUTE_WRITE_RESPONSE                 = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(2, 25)), //0x0519
    MSG_EVT_ATT_HANDLE_VALUE_NOTIFICATION              = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(2, 27)), //0x051B
    MSG_EVT_ATT_HANDLE_VALUE_INDICATION                = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(2, 29)), //0x051D
    MSG_EVT_ATT_HANDLE_VALUE_CONFIRMATION              = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(2, 30)), //0x051E

    MSG_EVT_GAP_DEVICE_INIT_DONE                       = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(4, 0 )), //0x0600
    MSG_EVT_GAP_DEVICE_DISCOVERY                       = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(4, 1 )), //0x0601
    MSG_EVT_GAP_ADVERT_DATA_UPDATE_DONE                = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(4, 2 )), //0x0602
    MSG_EVT_GAP_MAKE_DISCOVERABLE_DONE                 = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(4, 3 )), //0x0603
    MSG_EVT_GAP_END_DISCOVERABLE_DONE                  = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(4, 4 )), //0x0604
    MSG_EVT_GAP_LINK_ESTABLISHED                       = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(4, 5 )), //0x0605
    MSG_EVT_GAP_LINK_TERMINATED                        = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(4, 6 )), //0x0606
    MSG_EVT_GAP_LINK_PARAMETER_UPDATE                  = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(4, 7 )), //0x0607
    MSG_EVT_GAP_RANDOM_ADDRESS_CHANGED                 = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(4, 8 )), //0x0608
    MSG_EVT_GAP_SIGNATURE_UPDATED                      = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(4, 9 )), //0x0609
    MSG_EVT_GAP_AUTHENTICATION_COMPLETE                = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(4, 10)), //0x060A
    MSG_EVT_GAP_PASSKEY_NEEDED                         = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(4, 11)), //0x060B
    MSG_EVT_GAP_SLAVE_REQUESTED_SECURITY               = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(4, 12)), //0x060C
    MSG_EVT_GAP_DEVICE_INFORMATION                     = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(4, 13)), //0x060D
    MSG_EVT_GAP_BOND_COMPLETE                          = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(4, 14)), //0x060E
    MSG_EVT_GAP_PAIRING_REQUESTED                      = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(4, 15)), //0x060F

    MSG_EVT_EXT_COMMAND_STATUS                         = BUILD_VENDOR_EVT_MSG_ID(VENDOR_EVT_CODE(4,127)), //0x067F

    /// TCI Command
    MSG_CMD_TT_READ_LINK_INFO                          = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(7, 0 )), //0xFF80
    MSG_CMD_TT_MOVE_MASTER_ANCHOR                      = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(7, 1 )), //0xFF81
    MSG_CMD_TT_FIX_SLAVE_WIN_EXT                       = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(7, 2 )), //0xFF82
    MSG_CMD_TT_FIX_MASTER_CON_PARAMS                   = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(7, 3 )), //0xFF83
    MSG_CMD_TT_SET_ADV_PARAM_EX                        = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(7, 4 )), //0xFF84
    MSG_CMD_TT_SET_SCAN_PARAM_EX                       = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(7, 5 )), //0xFF85
    MSG_CMD_TT_SET_INIT_PARAM_EX                       = BUILD_VENDOR_CMD_MSG_ID(VENDOR_CMD_CODE(7, 6 )), //0xFF86

    /// TCI event
    MSG_EVT_CMP_TT_READ_LINK_INFO                      = MSGID_CMD2CMP(MSG_CMD_TT_READ_LINK_INFO),
    MSG_EVT_CMP_TT_MOVE_MASTER_ANCHOR                  = MSGID_CMD2CMP(MSG_CMD_TT_MOVE_MASTER_ANCHOR),
    MSG_EVT_CMP_TT_FIX_SLAVE_WIN_EXT                   = MSGID_CMD2CMP(MSG_CMD_TT_FIX_SLAVE_WIN_EXT),
    MSG_EVT_CMP_TT_FIX_MASTER_CON_PARAMS               = MSGID_CMD2CMP(MSG_CMD_TT_FIX_MASTER_CON_PARAMS),
    MSG_EVT_CMP_TT_SET_ADV_PARAM_EX                    = MSGID_CMD2CMP(MSG_CMD_TT_SET_ADV_PARAM_EX),
    MSG_EVT_CMP_TT_SET_SCAN_PARAM_EX                   = MSGID_CMD2CMP(MSG_CMD_TT_SET_SCAN_PARAM_EX),
    MSG_EVT_CMP_TT_SET_INIT_PARAM_EX                   = MSGID_CMD2CMP(MSG_CMD_TT_SET_INIT_PARAM_EX),
}co_msg_id_t;

/*********************************************************************
 * EXTERN VARIABLES
 */


/*********************************************************************
 * EXTERN FUNCTIONS
 */



#ifdef __cplusplus
}
#endif

#endif

