#ifndef LLC_EXT_SCAN_SECONDARY_SCANNING_H
#define LLC_EXT_SCAN_SECONDARY_SCANNING_H


void rom_llc_ext_scan_secondary_scanning_on_enable(stLlcExtScan_t* pstScan);

void rom_llc_ext_scan_secondary_scanning_on_disable(stLlcExtScan_t* pstScan);

void rom_llc_ext_scan_secondary_scanning_prepare_timing(stLlcExtScan_t* pstScan);

bool rom_llc_ext_scan_secondary_scanning_get_timing(stLlcExtScan_t* pstScan, stLlcExtScanTiming_t* pstTiming);

void rom_llc_ext_scan_secondary_scanning_on_received_extended_pdu_when_primary_scanning(stLlcExtScan_t* pstScan, stLlcAdvChannelPdu_t* pstPdu);

void rom_llc_ext_scan_secondary_scanning_on_scheduled(stLlcExtScan_t* pstScan);

uint32_t rom_llc_ext_scan_secondary_scanning_on_event_blocked (stLlcExtScan_t* pstScan);

EN_LLP_ERR_T rom_llc_ext_scan_secondary_scanning_config_llp(stLlcExtScan_t* pstScan, uint32_t u32MaxWorkWindowTimeUs);

void rom_llc_ext_scan_secondary_scanning_on_llp_fragment_start(stLlcExtScan_t* pstScan);

bool rom_llc_ext_scan_secondary_scanning_on_llp_fragment_stop(stLlcExtScan_t* pstScan);

EN_LLP_STATE_CMD_T rom_llc_ext_scan_secondary_scanning_on_llp_tx_end(stLlcExtScan_t* pstScan, stLlpTxEndReport_t *pstReport);

EN_LLP_STATE_CMD_T rom_llc_ext_scan_secondary_scanning_on_llp_rx_end(stLlcExtScan_t* pstScan, stLlpRxEndReport_t *pstReport);

#endif
