/**
 * @file i2s.h
 * @brief i2s driver
 * @date Wed 31 May 2017 07:15:29 PM CST
 * @author liqiang
 *
 * @defgroup I2S I2S
 * @ingroup PERIPHERAL
 * @brief I2S driver
 * @details I2S driver
 *
 * The I2S have three wires: serial data, word select and serial clock and
 * this interface is used for audio data transfer. The XH98xx I2S interface
 * supports both master and slave mode for transmitter and receiver.
 * The I2S supports the standard I2S frame format.
 *
 * @{
 *
 * @example example_audio.c
 * This is an example of how to use the i2s
 *
 */

#ifndef __I2S_H__
#define __I2S_H__

#ifdef __cplusplus
extern "C"
{
#endif

/*********************************************************************
 * INCLUDES
 */
#include "peripheral.h"


/*********************************************************************
 * MACROS
 */
/**
 * i2s rx clock and ws is generated by codec
 */
#define i2s_rx_clock_ws_generated_by_codec()   \
        do { XH_AUDIO->IF_CTRL |= AU_I2S_RX_MS_SEL_MASK; } while (0)

/**
 * i2s rx clock and ws is generated by gpio
 */
#define i2s_rx_clock_ws_generated_by_gpio()   \
        do { XH_AUDIO->IF_CTRL &= ~~AU_I2S_RX_MS_SEL_MASK; } while (0)

/**
 * i2s tx clock and ws is generated by codec
 */
#define i2s_tx_clock_ws_generated_by_codec()   \
        do { XH_AUDIO->IF_CTRL |= AU_I2S_TX_MS_SEL_MASK; } while (0)

/**
 * i2s tx clock and ws is generated by gpio
 */
#define i2s_tx_clock_ws_generated_by_gpio()   \
        do { XH_AUDIO->IF_CTRL &= ~~AU_I2S_TX_MS_SEL_MASK; } while (0)


#define I2S_IMR_TXFOM        (0x00000020UL)
#define I2S_IMR_TXFEM        (0x00000010UL)
#define I2S_IMR_RXFOM        (0x00000002UL)
#define I2S_IMR_RXDAM        (0x00000001UL)

/*********************************************************************
 * TYPEDEFS
 */
/// I2S work mode
typedef enum
{
    I2S_WORKMODE_SLAVE        = 0,
    I2S_WORKMODE_MASTER       ,
}i2s_workmode_t;

/// I2S PCM mode
typedef enum
{
    I2S_PCMMODE_STEREO        = 0,
    I2S_PCMMODE_MONO          ,
}i2s_pcmmode_t;

/// I2S bit width
typedef enum
{
    I2S_BITWIDTH_IGNORE     = 0,
    I2S_BITWIDTH_12BIT      ,
    I2S_BITWIDTH_16BIT      ,
    I2S_BITWIDTH_20BIT      ,
    I2S_BITWIDTH_24BIT      ,
    I2S_BITWIDTH_32BIT      ,
    I2S_BITWIDTH_64BIT      ,
    I2S_BITWIDTH_128BIT     ,
    I2S_BITWIDTH_192BIT     ,
}i2s_bitwidth_t;

/// I2S sample rate
typedef enum
{
    I2S_SAMPLE_8K           = 8000,
    I2S_SAMPLE_16K          = 16000,
    I2S_SAMPLE_32K          = 32000,
}i2s_sample_t;

/// i2s DMA configuration structure
typedef struct
{
    /// Enable fifo
    bool           use_fifo;
    /// DMA fifo buffer
    void          *buffer;
    /// DMA fifo buffer length
    uint32_t       buffer_len;
    /// DMA block linked list item
    dma_llip_t    *block_llip;
    /// DMA block linked list item num
    uint32_t       block_num;
    /// DMA event callback
    dma_callback_t callback;
}i2s_dma_config_t;



/// i2s configuration structure.
typedef struct
{
    /// sample rate
    i2s_sample_t     sample_rate;
    /// sample width
    i2s_bitwidth_t   sample_width;
    /// ws bit width
    i2s_bitwidth_t   ws_width;
    /// work mode
    i2s_workmode_t   workmode;
    /// pcm mode
    i2s_pcmmode_t    pcmmode;
} i2s_config_t;

/*********************************************************************
 * EXTERN VARIABLES
 */


/*********************************************************************
 * EXTERN FUNCTIONS
 */
/**
 * @brief i2s initialize
 *
 * @return None
 **/
void i2s_init(void);

/**
 * @brief i2s config
 *
 * @param[in] config  configuration @ref i2s_config_t
 *
 * @return None
 **/
void i2s_config(const i2s_config_t *config);

/**
 * @brief adc_dma_config()
 *
 * @param[in] dma  NULL: ADC will allocate a new dma; Not NULL: use it as ADC dma
 * @param[in] config  configuration @ref i2s_dma_config_t
 *
 * @retval NULL No DMA valid or error happen
 * @retval NOT_NULL: Current used DMA
 **/
XH_DMA_CH_Type *i2s_dma_config(XH_DMA_CH_Type *dma, const i2s_dma_config_t *config);

/**
 * @brief i2s start
 *
 * @return None
 **/
void i2s_start(void);

/**
 * @brief i2s stop
 *
 * @return None
 **/
void i2s_stop(void);

/**
 * @brief i2s config rx
 *
 * @param[in] config  configuration @ref i2s_config_t
 *
 * @return None
 **/
void i2s_rx_config(const i2s_config_t *config);



void i2s_config_tx_no_ws_and_sclk(i2s_config_t *config, bool bUse_dma);

void i2s_config_rx_gen_ws_and_sclk(i2s_config_t *config,bool bUse_dma);

void i2s_config_rx_no_ws_and_sclk(i2s_bitwidth_t bitwidth, bool bUse_dma);




/**
 * @brief i2s_dma_config() for rx
 *
 * @param[in] dma  NULL: ADC will allocate a new dma; Not NULL: use it as ADC dma
 * @param[in] config  configuration @ref i2s_dma_config_t
 *
 * @retval NULL No DMA valid or error happen
 * @retval NOT_NULL: Current used DMA
 **/
XH_DMA_CH_Type *i2s_rx_dma_config(XH_DMA_CH_Type *dma, const i2s_dma_config_t *config);

/**
 * @brief i2s start rx
 *
 * @return None
 **/
void i2s_rx_start(const i2s_config_t *config);


void i2s_start_tx_no_ws_and_sclk(void);
void i2s_start_rx_no_ws_and_sclk(void);
void i2s_start_rx_gen_ws_and_sclk(void);

/**
 * @brief i2s stop rx
 *
 * @return None
 **/
void i2s_rx_stop(void);

#ifdef __cplusplus
}
#endif

#endif

/** @} */

