/****************************************************************************
 * PAN216 Configuration File Generated by PAN216 ES Tool
 * 2024-12-25 14:40:34
 *****************************************************************************/
#ifndef _EASY_REG_H
#define _EASY_REG_H

#define EASY_RF_Channel         12
#define EASY_RF_TxPower         PAN216_TXPWR_0dBm
#define EASY_RF_DataRate        PAN216_DR_1Mbps
#define EASY_RF_ChipMode        PAN216_CHIPMODE_XN297
#define EASY_RF_WorkMode        PAN216_WORKMODE_NORMAL
#define EASY_RF_Crc             PAN216_CRC_2byte
#define EASY_RF_TxAddrWidth     PAN216_WIDTH_5BYTES
#define EASY_RF_TxAddr          {0xCC, 0xCC, 0xCC, 0xCC, 0xCC} 
#define EASY_RF_RxAddrWidth     PAN216_WIDTH_5BYTES
#define EASY_RF_RxAddr                                                      \
                                {                                           \
                                    true,  {0xCC, 0xCC, 0xCC, 0xCC, 0xCC},  \
                                    false, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC},  \
                                    false, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC},  \
                                    false, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC},  \
                                    false, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC},  \
                                    false, {0xCC, 0xCC, 0xCC, 0xCC, 0xCC},  \
                                }
#define EASY_RF_EnTxNoAck       1
#define EASY_RF_EnWhite         1
#define EASY_RF_crcSkipAddr     0
#define EASY_RF_scrSkipAddr     0
#define EASY_RF_Endian          1
#define EASY_RF_TxLen           32
#define EASY_RF_RxLen           32
#define EASY_RF_EnDPL           0
#define EASY_RF_TRxDelayTimeUs  0
#define EASY_RF_RxTimeoutUs     0
#define EASY_RF_AutoDelayUs     0
#define EASY_RF_AutoMaxCnt      3
#define EASY_RF_TxMode          PAN216_TX_MODE_SINGLE
#define EASY_RF_RxMode          PAN216_RX_MODE_CONTINOUS

#define PAN216_PAGE0TABLE  \
        {0x05,0xC8},       \
        {0x07,0x89},       \
        {0x08,0xA3},       \
        {0x09,0x20},       \
        {0x0A,0x20},       \
        {0x2A,0x41},       \
        {0x2B,0x00},       \
        {0x2C,0x00},       \
        {0x39,0x0C},       \
        {0x43,0x3A},       \
        {0x44,0x84},       \
        {0x55,0xDD},       \
        {0x56,0xC9},       \
        {0x57,0xB7},       \
        {0x5A,0x0F},       \
        {0x5B,0xFC},       \
        {0x5C,0xE8},       \
        {0x5D,0xD3},       \
        {0x5E,0x02},       \
        {0x5F,0x06},       \
        {0x60,0x0E},       \
        {0x61,0x3E},       \
        {0x66,0x34},       \
        {0x68,0x0D},       \
        {0x6E,0x20}

#define PAN216_PAGE1TABLE  \
        {0x27,0xCA},       \
        {0x37,0x15},       \
        {0x3A,0x14},       \
        {0x3C,0x13},       \
        {0x4C,0x48}

#endif
