/**
 * @file     sflash_p25q40u.h
 * @version  V1.0
 * @date     2021/06/18
 * @history 
 * @note
 * @attention
 *
 * THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS WITH CODING INFORMATION REGARDING THEIR 
 * PRODUCTS IN ORDER FOR THEM TO SAVE TIME. AS A RESULT, MAXSCEND SHALL NOT BE HELD LIABLE FOR ANY DIRECT, 
 * INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE 
 * USE MADE BY CUSTOMERS OF THE CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS.
 *
 * Copyright (c) 2016~2021, Maxscend Microelectronics Company Limited.
 * All rights reserved.
 */

#ifndef __SFLASH_P25Q40U_H__
#define __SFLASH_P25Q40U_H__


#define P25Q40U_CHIP_ID                    (0x136085)
#define P25Q40U_PROGRAM_TIME_US            (3000)
#define P25Q40U_PAGE_ERASE_TIME_US         (12000)
#define P25Q40U_CHIP_ERASE_TIME_US         (12000)

#define P25Q40U_ADDR_BITS                  (0x18)



#endif /* __SFLASH_P25Q40U_H__ */


