/**
 * @file     sflash.h
 * @version  V1.0
 * @date     2021/06/18
 * @history
 * @note
 * @attention
 *
 * THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIUS AT PROVIDING CUSTOMERS WITH CODING INFORMATION REGARDING THEIR
 * PRODUCTS IN ORDER FOR THEM TO SAVE TIME. AS A RESULT, MAXSCEND SHALL NOT BE HELD LIABLE FOR ANY DIRECT,
 * INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIUS ARISING FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE
 * USE MADE BY CUSTOMERS OF THE CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS.
 *
 * Copyright (c) 2016~2023, Maxscend Microelectronics Company Limited.
 * All rights reserved.
 */

#ifndef __SFLASH_H__
#define __SFLASH_H__

#include ".\puya\sflash_p25q40u.h"
#include ".\puya\sflash_p25q40su.h" // 512KB
#include ".\puya\sflash_p25q80su.h" // 1MB
#include ".\puya\sflash_p25q16su.h" // 2MB

#define SFLASH_CHIP_ID              (P25Q80SU_CHIP_ID)
#define SFLASH_PROGRAM_TIME_US      (P25Q80SU_PROGRAM_TIME_US)
#define SFLASH_PAGE_ERASE_TIME_US   (P25Q80SU_PAGE_ERASE_TIME_US)
#define SFLASH_SECTOR_ERASE_TIME_US (P25Q80SU_PAGE_ERASE_TIME_US)
#define SFLASH_CHIP_ERASE_TIME_US   (P25Q80SU_CHIP_ERASE_TIME_US)

#endif /* __SFLASH_H__ */
