#ifndef LLC_CHANNEL_MAP_UPDATE_PROCEDURE_H
#define LLC_CHANNEL_MAP_UPDATE_PROCEDURE_H

void rom_llc_channel_map_update_procedure_init(stLlcConnectionRole_t *pstRole);

bool rom_llc_channel_map_update_procedure_peer_initiated_init(stLlcConnectionRole_t *pstRole, stLlcCtrlProcedure_t* pstProcedure, stLlcDataChannelPdu_t* pstFirstPdu);

uint8_t rom_llc_channel_map_update_procedure_self_initiated_init(stLlcConnectionRole_t *pstRole, stLlcCtrlProcedure_t* pstProcedure, bool bPending, uint8_t pu8ChannelMap[5]);

EN_LLC_CTRL_PROCEDURE_ERR_T rom_llc_channel_map_update_procedure_on_recv_ctrl_pdu(stLlcConnectionRole_t *pstRole, stLlcCtrlProcedure_t* pstProcedure, stLlcDataChannelPdu_t* pstCtrlPdu);


EN_LLC_CTRL_PROCEDURE_ON_EVENT_CLOSED_RESULT_T rom_llc_channel_map_update_procedure_on_conn_event_closed(stLlcConnectionRole_t *pstRole, stLlcCtrlProcedure_t* pstProcedure);

#endif
